baseURL = "https://www.bizarretheory.com/"
languageCode = "it"
DefaultContentLanguage = "it"
title = "Bizarre Theory - Un blog di Haiku di Giacomo Pellegrini"
theme = "story"

[params]
  author = "Giacomo Pellegrini"
  twitter = "supercd"
  classes = ["feature-justify"]