baseURL = "https://www.bizarretheory.com/"
languageCode = "it"
DefaultContentLanguage = "it"
title = "Bizarre Theory"
paginate = 5
theme = "story"
enableRobotsTXT = true
googleAnalytics = "UA-138137025-1"

[params]
  author = "Giacomo Pellegrini"
  facebook = "bizarretheory"
  twitter = "supercd"

[[menu.social]]
  name = "Facebook"
  title = "fab fa-facebook-square"
  url = "https://www.facebook.com/bizarretheory"

[[menu.main]]
  name = "Haiku"
  title = "Haiku"
  url = "/haiku/"

[outputs]
home = ["HTML", "JSON", "RSS"]
page = ["HTML"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
taxonomyTerm = ["HTML", "RSS"]